sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t syedrohaan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true syedrohaan/react-test npm test

after_success:
  - docker build -t syedrohaan/multi-client ./client
  - docker build -t syedrohaan/multi-nginx ./nginx
  - docker build -t syedrohaan/multi-server ./server
  - docker build -t syedrohaan/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push syedrohaan/multi-client
  - docker push syedrohaan/multi-nginx
  - docker push syedrohaan/multi-server
  - docker push syedrohaan/multi-worker
